name: Build ISO

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build ISO
        run: .github/build.sh

      - name: Upload ISO
        uses: actions/upload-artifact@v1
        with:
          name: ShrineDist.ISO
          path: .build/Shrine.out/Tmp/ShrineDist.ISO.C
